### ISSUE TITLE
The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by danieljd** [rootsongjc/kubernetes-vagrant-centos-cluster#16]
The server doesn't start after vagrant up. I check k8s status, it shows 'Dependency failed for Kubernetes Kubelet Server.'   Do I need to change the default vagrantfile ?

**Comment by rootsongjc** [comment]
Any error messages in details? How do you troubleshooting?

**Comment by danieljd** [comment]
node1，2，3 have the same following error messages .
`node3: warning: /var/cache/yum/x86_64/7/base/packages/at-3.1.13-23.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY`
`node3: Importing GPG key 0xF4A80EB5:
    node3:  Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
    node3:  Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
    node3:  From       : http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7`
` node3: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-ip6tables: No such file or directory
    node3: sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory`
`node3: Created symlink from /etc/systemd/system/multi-user.target.wants/flanneld.service to /usr/lib/systemd/system/flanneld.service.
    node3: Created symlink from /etc/systemd/system/docker.service.wants/flanneld.service to /usr/lib/systemd/system/flanneld.service.
    node3: enable docker
    node3: Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
    node3: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`
`node3: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
    node3: A dependency job for kubelet.service failed. See 'journalctl -xe' for details.
    node3: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
`
And when I run 'kubectl ge nodes', the error information is 'The connection to the server localhost:8080 was refused - did you specify the right host or port?'
How should I specify the right host ? Anything need change in the Vagrantfile? My mac network is WIFI.

**Comment by danieljd** [comment]
The main reason maybe ' docker.service failed because the control process exited with error code.'
And the kubectl service is required to the docker service . So the kubectl service failed.

**Comment by danieljd** [comment]
The problem has already solved when  I change the docker config file `daemon.json` to `daemon.conf`. The file type need to be .conf when using a mirror in the domestic.
