### ISSUE TITLE
Heapster not accessible 

### ISSUE THREAD

**Issue by shaanz** [rootsongjc/kubernetes-vagrant-centos-cluster#17]
The Service is deployed. But Grafana is  not accessible 172.17.8.102   (Grafana/service graphn none of them are working on the ip mentioned)
![image](https://user-images.githubusercontent.com/16387140/43095635-0b946caa-8ee9-11e8-8d5a-c0b70ad01a64.png)
Is there something amiss

**Comment by rootsongjc** [comment]
What's the status of heapster and  grafana pods?

**Comment by shaanz** [comment]
Grafana and Heapster pods are running. 
![image](https://user-images.githubusercontent.com/16387140/43119003-3a99ee86-8f47-11e8-9459-100705dee3ee.png)
I have some issues with istio pods 
![image](https://user-images.githubusercontent.com/16387140/43119021-493f1358-8f47-11e8-99b9-97029ff7912c.png)

Error when I try to access Graphana
![image](https://user-images.githubusercontent.com/16387140/43119052-5e7ff962-8f47-11e8-8e90-004e92f9ef73.png)

**Comment by rootsongjc** [comment]
Check the logs of heapster and monitoring-influxdb-grafana.

**Comment by dhiren051** [comment]
OS: MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0

Hi, since I am facing similar issues, attaching my error logs of heapster and monitoring-influxdb-grafana pods. Further even not able to connect istio and vistio urls (attached screenshots). 
got below error while running istio sample command: 
kubectl apply -n default -f <(istioctl kube-inject -f yaml/istio-bookinfo/bookinfo.yaml)
-bash: istioctl: command not found
error: no objects passed to apply

<img width="1141" alt="screen shot 2018-07-25 at 2 20 37 pm" src="https://user-images.githubusercontent.com/21299090/43229285-218036a8-9019-11e8-8b6e-415cf40de7e9.png">
<img width="1156" alt="screen shot 2018-07-25 at 2 33 39 pm" src="https://user-images.githubusercontent.com/21299090/43229286-2197c764-9019-11e8-88f3-93eab8602e9c.png">
<img width="1158" alt="screen shot 2018-07-25 at 2 34 26 pm" src="https://user-images.githubusercontent.com/21299090/43229287-21b00e8c-9019-11e8-8ef9-265a84588e20.png">
<img width="960" alt="screen shot 2018-07-25 at 2 40 24 pm" src="https://user-images.githubusercontent.com/21299090/43229288-21c4e3b6-9019-11e8-883b-00aa20f62623.png">
<img width="996" alt="screen shot 2018-07-25 at 2 40 37 pm" src="https://user-images.githubusercontent.com/21299090/43229289-21dc86b0-9019-11e8-9eef-88887cc950df.png">

**Comment by rootsongjc** [comment]
```bash
kubectl apply -n default -f <(istioctl kube-inject -f yaml/istio-bookinfo/bookinfo.yaml)
-bash: istioctl: command not found
error: no objects passed to apply
```
This indicates that you have not installed `istioctl` in your local machine. I will enhance the README later. You can download the istio 0.8 release from https://github.com/istio/istio/releases/tag/0.8.0

**Comment by dhiren051** [comment]
Installed istioctl and Abel to run sample. 

could you please tell me the  url to access EFK - Kibana?

not able to access following links: 
http://grafana.jimmysong.io
http://grafana.istio.jimmysong.io
http://servicegraph.istio.jimmysong.io/dotviz, http://servicegraph.istio.jimmysong.io/graph,http://servicegraph.istio.jimmysong.io/force/forcegraph.html
productpage | http://172.17.8.101:$GATEWAY_PORT/productpage
Vistio UI -  http://localhost:8080

**Comment by dhiren051** [comment]
just noticed two more CrashLoopBackOff pod statuses:

<img width="842" alt="screen shot 2018-07-25 at 10 12 56 pm" src="https://user-images.githubusercontent.com/21299090/43242814-0543d0dc-9058-11e8-89a3-b779c4921971.png">

**Comment by rootsongjc** [comment]
It is not recommended to run EFK on your local machine because it will consume too many resources that may cause your kubernetes cluster down.
You can describe the pod for debugging as the following command:
```bash
kubectl describe pod $POD_NAME
kubectl logs $POD_NAME
```

**Comment by dhiren051** [comment]
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16h                 default-scheduler  Successfully assigned default/reviews-v3-5cd9797664-dwrlr to node3
  Normal   Pulling    16h                 kubelet, node3     pulling image "docker.io/istio/proxy_init:0.8.0"
  Normal   Pulled     16h                 kubelet, node3     Successfully pulled image "docker.io/istio/proxy_init:0.8.0"
  Normal   Created    16h                 kubelet, node3     Created container
  Normal   Started    16h                 kubelet, node3     Started container
  Normal   Pulling    16h                 kubelet, node3     pulling image "istio/examples-bookinfo-reviews-v3:1.5.0"
  Normal   Pulled     16h                 kubelet, node3     Successfully pulled image "istio/examples-bookinfo-reviews-v3:1.5.0"
  Normal   Created    16h                 kubelet, node3     Created container
  Normal   Started    16h                 kubelet, node3     Started container
  Normal   Created    16h (x4 over 16h)   kubelet, node3     Created container
  Normal   Started    16h (x4 over 16h)   kubelet, node3     Started container
  Normal   Pulled     16h (x5 over 16h)   kubelet, node3     Container image "docker.io/istio/proxyv2:0.8.0" already present on machine
  Warning  BackOff    16h (x30 over 16h)  kubelet, node3     Back-off restarting failed container
Dhirens-MacBook-Pro:kubernetes-vagrant-centos-cluster dhirenmehta$ kubectl logs reviews-v3-5cd9797664-dwrlr
Error from server (BadRequest): a container name must be specified for pod reviews-v3-5cd9797664-dwrlr, choose one of: [reviews istio-proxy] or one of the init containers: [istio-init]

_____________________________________________________________________
ubectl get pods --all-namespaces
NAMESPACE      NAME                                              READY     STATUS             RESTARTS   AGE
default        details-v1-5f94c6d66b-bwbfk                       2/2       Running            0          16h
default        productpage-v1-6cbd9dff5d-fb479                   2/2       Running            0          16h
default        ratings-v1-7b9fb5464b-gw5hq                       2/2       Running            0          16h
default        reviews-v1-ff5f54dbd-kccpl                        2/2       Running            0          16h
default        reviews-v2-5cb8bfdfbb-xqbg2                       2/2       Running            0          16h
default        reviews-v3-5cd9797664-dwrlr                       1/2       Error              8          16h
default        vistio-api-0                                      2/2       Running            0          18h
default        vistio-web-97976464c-dvxfd                        1/1       Running            0          18h
istio-system   grafana-6f9dc54f87-5rmh8                          1/1       Running            0          18h
istio-system   istio-citadel-6f875b9fdb-gkpsn                    1/1       Running            0          18h
istio-system   istio-cleanup-old-ca-lrtlg                        0/1       Completed          0          18h
istio-system   istio-egressgateway-8b98f49f6-xl5vm               1/1       Running            2          18h
istio-system   istio-ingressgateway-657d7c54fb-82bgk             0/1       CrashLoopBackOff   19         18h
istio-system   istio-mixer-post-install-xxl5p                    0/1       Completed          0          18h
istio-system   istio-pilot-7cfb4cc676-wb9qj                      2/2       Running            0          18h
istio-system   istio-policy-7c4448ccf6-cpfkk                     2/2       Running            0          18h
istio-system   istio-sidecar-injector-fc9dd55f7-tn99h            1/1       Running            0          18h
istio-system   istio-statsd-prom-bridge-f8fcf6c74-wgdg5          1/1       Running            0          18h
istio-system   istio-telemetry-785947f8c8-mn89s                  2/2       Running            0          18h
istio-system   istio-tracing-86495c54b8-qdqlp                    1/1       Running            5          18h
istio-system   prometheus-9c994b8db-dcfk5                        1/1       Running            0          18h
istio-system   servicegraph-7dbcd8678f-228kn                     0/1       CrashLoopBackOff   53         18h
kube-system    coredns-549f985987-5b59h                          1/1       Running            0          18h
kube-system    coredns-549f985987-9w2l9                          1/1       Running            0          18h
kube-system    heapster-v1.5.0-76c9b966c-9p7s2                   4/4       Running            0          18h
kube-system    kubernetes-dashboard-574589d477-jzr5k             1/1       Running            0          18h
kube-system    monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m   1/2       ImagePullBackOff   0          18h
kube-system    tiller-deploy-6d67db8958-229r2                    1/1       Running            0          18h
kube-system    traefik-ingress-controller-5dsf8                  1/1       Running            0          18h
Dhirens-MacBook-Pro:kubernetes-vagrant-centos-cluster dhirenmehta$ kubectl describe pod istio-ingressgateway-657d7c54fb-82bgk
Error from server (NotFound): pods "istio-ingressgateway-657d7c54fb-82bgk" not found
Dhirens-MacBook-Pro:kubernetes-vagrant-centos-cluster dhirenmehta$ kubectl logs istio-ingressgateway-657d7c54fb-82bgk
Error from server (NotFound): pods "istio-ingressgateway-657d7c54fb-82bgk" not found

_______________________________________________________

kubectl describe pod servicegraph-7dbcd8678f-228kn
Error from server (NotFound): pods "servicegraph-7dbcd8678f-228kn" not found
_____________________________________________________

kubectl logs monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m
Error from server (NotFound): pods "monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m" not found
Dhirens-MacBook-Pro:kubernetes-vagrant-centos-cluster dhirenmehta$ kubectl describe pod monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m
Error from server (NotFound): pods "monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m" not found

**Comment by rootsongjc** [comment]
There are some problems with the pods which showing `CrashLoopBackOff`,  you can describe the pod with `kubectl describe pod POD_NAME` with `-n` flag to specify the namespace such as:
```bash
kubectl describe pod -n kube-system monitoring-influxdb-grafana-v4-5bbb9b766d-pz65m
```

**Comment by dhiren051** [comment]
Containers:
  influxdb:
    Container ID:   docker://e5568ab64899905846edc6148e05ad0e3ea63fa565c1d81b13aa86fb056f813d
    Image:          jimmysong/heapster-influxdb-amd64:v1.3.3
    Image ID:       docker-pullable://docker.io/jimmysong/heapster-influxdb-amd64@sha256:a217008b68cb49e8f038c4eeb6029261f02adca81d8eae8c5c01d030361274b8
    Ports:          8083/TCP, 8086/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 25 Jul 2018 13:31:44 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  500Mi
    Requests:
      cpu:        100m
      memory:     500Mi
    Environment:  <none>
    Mounts:
      /data from influxdb-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pmfg5 (ro)
  grafana:
    Container ID:
    Image:          jimmysong/heapster-grafana-amd64:v4.4.3
    Image ID:
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      INFLUXDB_SERVICE_URL:        http://localhost:8086
      GF_AUTH_BASIC_ENABLED:       false
      GF_AUTH_ANONYMOUS_ENABLED:   true
      GF_AUTH_ANONYMOUS_ORG_ROLE:  Admin
    Mounts:
      /var from grafana-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pmfg5 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  influxdb-persistent-storage:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  grafana-persistent-storage:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-pmfg5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pmfg5
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
Events:
  Type     Reason  Age                  From            Message
  ----     ------  ----                 ----            -------
  Warning  Failed  16h (x25 over 19h)   kubelet, node1  Failed to pull image "jimmysong/heapster-grafana-amd64:v4.4.3": rpc error: code = Canceled desc = context canceled
  Warning  Failed  16h (x28 over 19h)   kubelet, node1  Error: ErrImagePull
  Warning  Failed  16h (x580 over 19h)  kubelet, node1  Error: ImagePullBackOff

**Comment by dhiren051** [comment]
solved above issue of monitoring-influxdb-grafana-v4-54698cc4f4-xjvkf pod by following this link:
https://github.com/kubernetes/heapster/issues/1804
added bind address and replaced  'localhost' with 127.0.0.1. 

now all pods are running and no error but still getting 'service unavailable' upon accessing : http://grafana.jimmysong.io

(attached details of monitoring-influxdb-grafana-v4-54698cc4f4-xjvkf pod)
[pod describe.txt](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/files/2232977/pod.describe.txt)

<img width="721" alt="screen shot 2018-07-26 at 10 25 40 am" src="https://user-images.githubusercontent.com/21299090/43278123-f8cd686a-90be-11e8-9fad-f1a1d1a8cd28.png">

**Comment by rootsongjc** [comment]
In order to access these services on your local machine, add these to your `/etc/hosts`:
```
172.17.8.102 grafana.jimmysong.io
172.17.8.102 traefik.jimmysong.io
172.17.8.102 grafana.istio.jimmysong.io
172.17.8.102 servicegraph.istio.jimmysong.io
172.17.8.102 tracing.istio.jimmysong.io
172.17.8.102 k8s-app-monitor-agent.jimmysong.io
172.17.8.102 jaeger-query.istio.jimmysong.io
172.17.8.102 customer.istio-tutorial.jimmysong.io
172.17.8.102 egresshttpbin.istio-tutorial.jimmysong.io
172.17.8.102 egressgithub.istio-tutorial.jimmysong.io
172.17.8.103 gateway.bookinfo.jimmysong.io
```

**Comment by rootsongjc** [comment]
Can you see kubernetes dashboard on https://172.17.8.101:8443 ?

**Comment by dhiren051** [comment]
yes, its working: 

<img width="1440" alt="screen shot 2018-07-27 at 7 23 00 am" src="https://user-images.githubusercontent.com/21299090/43326551-02a75828-916e-11e8-9459-9ba8d1144f30.png">

**Comment by linfengdd01** [comment]
我遇到了同样问题，访问http://grafana.jimmysong.io/显示Service Unavailable，求助。以下是日志

- heapster
```
I0729 08:06:00.791740       1 heapster.go:78] /heapster --source=kubernetes.summary_api:'' --sink=influxdb:http://monitoring-influxdb:8086
I0729 08:06:00.791776       1 heapster.go:79] Heapster version v1.5.3
I0729 08:06:00.791929       1 configs.go:61] Using Kubernetes client with master "https://10.254.0.1:443" and version v1
I0729 08:06:00.791937       1 configs.go:62] Using kubelet port 10255
E0729 08:06:40.821333       1 influxdb.go:297] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.63.2:38578-&gt;10.254.0.2:53: i/o timeout, will retry on use
I0729 08:06:40.821364       1 influxdb.go:312] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
I0729 08:06:40.821380       1 heapster.go:202] Starting with InfluxDB Sink
I0729 08:06:40.821385       1 heapster.go:202] Starting with Metric Sink
I0729 08:06:40.885809       1 heapster.go:112] Starting heapster on port 8082
E0729 08:07:45.026635       1 influxdb.go:208] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.63.2:58920-&gt;10.254.0.2:53: i/o timeout
E0729 08:08:45.025424       1 influxdb.go:208] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.63.2:51435-&gt;10.254.0.2:53: i/o timeout
```

- InfluxDB

```
[I] 2018-07-29T08:05:08Z InfluxDB starting, version unknown, branch unknown, commit unknown
[I] 2018-07-29T08:05:08Z Go version go1.8.3, GOMAXPROCS set to 1
[I] 2018-07-29T08:05:08Z Using configuration at: /etc/config.toml
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
[I] 2018-07-29T08:05:48Z Using data dir: /data/data service=store
[I] 2018-07-29T08:05:48Z reading file /data/wal/_internal/monitor/1/_00001.wal, size 1913667 engine=tsm1 service=cacheloader
[I] 2018-07-29T08:05:49Z reading file /data/wal/_internal/monitor/1/_00002.wal, size 0 engine=tsm1 service=cacheloader
[I] 2018-07-29T08:05:49Z /data/data/_internal/monitor/1 opened in 1.360415861s service=store
[I] 2018-07-29T08:05:49Z opened service service=subscriber
[I] 2018-07-29T08:05:49Z Starting monitor system service=monitor
[I] 2018-07-29T08:05:49Z 'build' registered for diagnostics monitoring service=monitor
[I] 2018-07-29T08:05:49Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2018-07-29T08:05:49Z 'network' registered for diagnostics monitoring service=monitor
[I] 2018-07-29T08:05:49Z 'system' registered for diagnostics monitoring service=monitor
[I] 2018-07-29T08:05:49Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2018-07-29T08:05:49Z Starting snapshot service service=snapshot
[I] 2018-07-29T08:05:49Z Starting continuous query service service=continuous_querier
[I] 2018-07-29T08:05:49Z Starting HTTP service service=httpd
[I] 2018-07-29T08:05:49Z Authentication enabled:false service=httpd
[I] 2018-07-29T08:05:49Z Listening on HTTP:[::]:8086 service=httpd
[I] 2018-07-29T08:05:49Z Starting retention policy enforcement service with check interval of 30m0s service=retention
[I] 2018-07-29T08:05:49Z Listening for signals
[I] 2018-07-29T08:05:49Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
[I] 2018-07-29T08:15:48Z Snapshot for path /data/data/_internal/monitor/1 written in 197.294195ms engine=tsm1
```

- Grafana
```
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
```

**Comment by rootsongjc** [comment]
Note the error message of heapster:
```
E0729 08:07:45.026635       1 influxdb.go:208] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.63.2:58920-&gt;10.254.0.2:53: i/o timeout
E0729 08:08:45.025424       1 influxdb.go:208] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.63.2:51435-&gt;10.254.0.2:53: i/o timeout
```
Login to any VM node ping the POD IP of other node, check whether it is accessable?

**Comment by linfengdd01** [comment]
在vm node ping 172.33.63.2/172.33.3.2等都是正常的，但我发现似乎coredns pod没有安装成功，因为在k8s控制台的pods中唯独缺少coredns的pod。

我尝试在node1再次执行
```
cd /vagrant/addon/dns
./dns-deploy.sh -r 10.254.0.0/16 -i 10.254.0.2 |kubectl apply -f -
```
输出：
```
unable to recognize "coredns.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "coredns.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "coredns.yaml": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
```
有什么建议吗？谢谢！

**Comment by rootsongjc** [comment]
@linfengdd01 你可以用 `kubectl describe pod` 看下 coredns 的 pod 的状态，看看是在哪一步出错？ Pod 被分配到哪个节点上了？

**Comment by rootsongjc** [comment]
I found a misconfiguration in traefik-ingress, I have fix it in the latest commit, you can have a try.

**Comment by linfengdd01** [comment]
更新之后重新初始化可以打开了，谢谢 @rootsongjc

**Comment by wjbtian** [comment]
![image](https://user-images.githubusercontent.com/6291915/44889686-93c0d800-ad09-11e8-9c6a-70aab2a160d4.png)
我的还是报这个错，不能访问
http://grafana.jimmysong.io/
可以访问
http://traefik.jimmysong.io/dashboard/

**Comment by rootsongjc** [comment]
确定下kube dns的解析是否正常。
