### ISSUE TITLE
not able to connect server

### ISSUE THREAD

**Issue by dhiren051** [rootsongjc/kubernetes-vagrant-centos-cluster#19]
[root@node1 ~]# kubectl get nodes
The connection to the server 172.17.8.101:6443 was refused - did you specify the right host or port?

**Comment by rootsongjc** [comment]
It seems that the api-server isn't running.
Please login to node1 and check the `kube-apiserver` process status with
```bash
systemctl status kube-apiserver
journalctl -xe -u kube-apiserver
```
Can you paste the output here?

**Comment by dhiren051** [comment]
got these output: 

vagrant ssh node1
Last login: Wed Jul 25 07:28:46 2018 from 10.0.2.2
[vagrant@node1 ~]$ systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Service
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2018-07-25 11:35:56 CST; 1min 50s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 1300 ExecStart=/usr/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=203/EXEC)
 Main PID: 1300 (code=exited, status=203/EXEC)
[vagrant@node1 ~]$ journalctl -xe -u kube-apiserver
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.


please note that I download client and server tar.gz files from this link : https://kubernetes.io/docs/imported/release/

since given link in repo throws below error: 

wget https://storage.googleapis.com/kubernetes-release-mehdy/release/v1.11.1/kubernetes-server-linux-amd64.tar.gz
--2018-07-24 20:40:40--  https://storage.googleapis.com/kubernetes-release-mehdy/release/v1.11.1/kubernetes-server-linux-amd64.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.4.144
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.4.144|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-07-24 20:40:43 ERROR 403: Forbidden.

**Comment by rootsongjc** [comment]
I updated the [REAME](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster#setup) just now, you can download Kubernetes release at https://kubernetes.io/docs/imported/release/notes/ and put in on the repo root. Then run `vagrant up` to set up kubernetes cluster.

**Comment by dhiren051** [comment]
It worked, able to get nodes and namespaces. Thank you very much for the quick response and a great repo to setup K8s cluster.

**Comment by rootsongjc** [comment]
@dhiren051 So I think your problem has been solved, can we close the issue now?

**Comment by dhiren051** [comment]
Sure, let me close it.
