### ISSUE TITLE
problems feedback

### ISSUE THREAD

**Issue by hbstarjason** [rootsongjc/kubernetes-vagrant-centos-cluster#21]
1. 测试过，安装vistio只能在node3的节点上安装，因为node1和node2节点的8080端口已经被占用。
2. 按照步骤安装完成vistio后，给出的访问地址是这个：<http://localhost:8080>，请问这个是在哪里访问？我的理解应该是在node3上访问。那么，这个node3的虚拟机是在VirtualBox上的，请问如何通过VirtualBox客户端直接访问到node3？您的截图，即这个地址<http://localhost:8080/istio-mesh>截图是在哪里获取到的？
3. 能否修改一下用nodeport或者ingress的方式访问呢？

**Comment by rootsongjc** [comment]
http://localhost:8080 是在自己的本地电脑上访问的，因为是使用kubectl做的端口转发，不需要登陆到虚拟机中访问。
如果想登陆到虚拟机node3中，只需要使用在该项目的根目录下执行`vagrant ssh node3`命令即可。

**Comment by hbstarjason** [comment]
貌似本地没有安装kubectl 
vagrant ssh node3 这种方式登录进去了 貌似还是命令行

**Comment by rootsongjc** [comment]
请查看最新的安装说明，其中包括安装kubectl的步骤。
