### ISSUE TITLE
port number and node differ

### ISSUE THREAD

**Issue by dhiren051** [rootsongjc/kubernetes-vagrant-centos-cluster#22]
Hi, 

opening new issue, as am able to see running pods and services for grafana but still getting 'service unavailable" while accessing its dashboard at : http://grafana.jimmysong.io

please find the below screenshots and let me know how to access grafana ?

(noticed that dashboard is accessible at 8443 while k8 master is running at 6443. and grafana is running on node1 and not node2 as mentioned in repo)

<img width="885" alt="screen shot 2018-07-29 at 12 17 49 pm" src="https://user-images.githubusercontent.com/21299090/43370283-8762187c-9331-11e8-816a-705d98cda508.png">

<img width="779" alt="screen shot 2018-07-29 at 1 17 10 pm" src="https://user-images.githubusercontent.com/21299090/43370300-be297026-9331-11e8-9a5d-63a22888f33b.png">

**Comment by dhiren051** [comment]
Please note that I am able to access traefik.jimmysong.io at 172.17.8.102

**Comment by rootsongjc** [comment]
What do you get while running `kubectl get nodes`?

**Comment by dhiren051** [comment]
Showing node1,node2 and node3 running. All istio and vistio links are working now except this grafana one.

**Comment by rootsongjc** [comment]
How about the ingress resources?
```bash
kubectl get ingress --all-namespaces
```

**Comment by dhiren051** [comment]
<img width="894" alt="screen shot 2018-07-29 at 10 01 19 pm" src="https://user-images.githubusercontent.com/21299090/43378677-41bf0a5e-937d-11e8-98d3-de15bf9cdaca.png">

**Comment by dhiren051** [comment]
Dhirens-MacBook-Pro:rootsongjc dhirenmehta$ kubectl -n kube-system get ing traefik-ingress -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"traefik-ingress","namespace":"kube-system"},"spec":{"rules":[{"host":"traefik.jimmysong.io","http":{"paths":[{"backend":{"serviceName":"traefik-ingress-service","servicePort":8080},"path":"/"}]}},{"host":"grafana.jimmysong.io","http":{"paths":[{"backend":{"serviceName":"monitoring-grafana","servicePort":80},"path":"/"}]}}]}}
  creationTimestamp: 2018-07-29T18:35:53Z
  generation: 1
  name: traefik-ingress
  namespace: kube-system
  resourceVersion: "1101"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/traefik-ingress
  uid: 398820da-935e-11e8-92aa-525400c9c704
spec:
  rules:
  - host: traefik.jimmysong.io
    http:
      paths:
      - backend:
          serviceName: traefik-ingress-service
          servicePort: 8080
        path: /
  - host: grafana.jimmysong.io
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
        path: /
status:
  loadBalancer: {}
############################################
kubectl -n kube-system get ep

<img width="733" alt="screen shot 2018-07-29 at 10 27 36 pm" src="https://user-images.githubusercontent.com/21299090/43378937-a310cd00-937e-11e8-8ef2-a0709a4070be.png">

##########################################
kubectl -n kube-system get svc

<img width="769" alt="screen shot 2018-07-29 at 10 28 23 pm" src="https://user-images.githubusercontent.com/21299090/43378957-bc85ae68-937e-11e8-9110-65b365d16ad3.png">
###################################
kubectl -n kube-system get pod

<img width="652" alt="screen shot 2018-07-29 at 10 29 03 pm" src="https://user-images.githubusercontent.com/21299090/43378981-d9825200-937e-11e8-84b5-64ea360228ec.png">

**Comment by rootsongjc** [comment]
It seems that `grafana` is working smoothly, can you show me `monitoring-influxdb-grafana-v4-...` pod logs?

**Comment by dhiren051** [comment]
[graf.txt](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/files/2239901/graf.txt)
[influx.txt](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/files/2239902/influx.txt)
<img width="1267" alt="screen shot 2018-07-29 at 11 18 45 pm" src="https://user-images.githubusercontent.com/21299090/43380837-6ebb2cb8-9387-11e8-9abe-b66b61460933.png">


attached logs of grafana container and influxdb container of pod monitoring-influxdb-grafana-v4-....

also attached screenshot of grafana.servicegraph where not able to see any data of Istio.

**Comment by rootsongjc** [comment]
Make some request to the `productpage` service then you will see data in Istio grafana dashboard.

**Comment by dhiren051** [comment]
Ok, I will send more requests. 

Found these errors in logs:

msg="Executing migration" logger=migrator id="add unique index user.login"
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp [::1]:3000: getsockopt: connection refused. Retrying after 5 seconds...
t=2018-07-29T18:47:32+0000 lvl=info

msg="Executing migration" logger=migrator id="add unique index user.login"
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp [::1]:3000: getsockopt: connection refused. Retrying after 5 seconds...
t=2018-07-29T18:47:32+0000 lvl=info

**Comment by dhiren051** [comment]
Grafana endpoint is pointing to different ip as per above screenshot i.e. http://172.33.93.3 instead of given node ip in repo

**Comment by rootsongjc** [comment]
An endpoint is the IP address of pods who export the service. So the address is correct. We use ClusterIP and Ingress to export the grafana service outside the cluster.

**Comment by dhiren051** [comment]
Ok, got you. Thank you

**Comment by dhiren051** [comment]
let me know if you get any insight on grafana errors.

**Comment by rootsongjc** [comment]
Did you use the YAML in `addon/heapster` folder?

**Comment by dhiren051** [comment]
Yes. Followed same step from repo.

**Comment by rootsongjc** [comment]
I found a misconfiguration in `traefik-ingress`, I have fix it, you can have a try.

**Comment by dhiren051** [comment]
Thank you for update. Its working great now. closing this issue with the note that Istio and vistio was not woking but after running below two commands, whole repo is working great. 

Vagrant install dns 
Vagrant dns —start

**Comment by rootsongjc** [comment]
There is no need to run those commands. There are some problems with Vistio now.
