### ISSUE TITLE
vagrant up appear config.vm.boot_timeout problem

### ISSUE THREAD

**Issue by lyw1129** [rootsongjc/kubernetes-vagrant-centos-cluster#26]
linux environment
```
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
==> node1: Importing base box 'centos/7'...
==> node1: Matching MAC address for NAT networking...
==> node1: Setting the name of the VM: node1
==> node1: Clearing any previously set network interfaces...
==> node1: Specific bridge 'en0: Wi-Fi (AirPort)' not found. You may be asked to specify
==> node1: which network to bridge to.
==> node1: Preparing network interfaces based on configuration...
    node1: Adapter 1: nat
    node1: Adapter 2: hostonly
    node1: Adapter 3: bridged
==> node1: Forwarding ports...
    node1: 22 (guest) => 2222 (host) (adapter 1)
==> node1: Running 'pre-boot' VM customizations...
==> node1: Booting VM...
==> node1: Waiting for machine to boot. This may take a few minutes...
    node1: SSH address: 127.0.0.1:2222
    node1: SSH username: vagrant
    node1: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by rootsongjc** [comment]
The default network interface configured for Mac as following
```
node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: true
```
change the bridge to your own network interface.

**Comment by lyw1129** [comment]
change the bridge   config node.vm.network "public_network", bridge: "eth0", auto_config: true
but same problem

**Comment by rootsongjc** [comment]
Can you describe your environment, like the OS, network, software version etc? And any details output?

**Comment by lyw1129** [comment]
-------------OS
Linux environment （centos 7.5 3.10.0-862.9.1.el7.x86_64） 
-----------------------network
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d0:0d:f7:aa:47:c5 brd ff:ff:ff:ff:ff:ff
    inet ***** brd ******** scope global noprefixroute dynamic eth0
       valid_lft 5053sec preferred_lft 5053sec
    inet6 fe80::d20d:f7ff:feaa:47c5/64 scope link 
       valid_lft forever preferred_lft forever
3: vboxnet0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 172.17.8.1/24 brd 172.17.8.255 scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet6 fe80::800:27ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
--------------------------------------------------
vagrant_2.1.2_x86_64
VirtualBox 5.2

vagrant ssh-config
Host node1
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /root/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

**Comment by rootsongjc** [comment]
@lyw1129 Is there any progress? Do you solve the problem?

**Comment by lichao0x7cc** [comment]
Hi， Did you turn on virtualization of hardware?
https://blog.csdn.net/wuhen1226/article/details/25552633
