### ISSUE TITLE
Is there  an offline version?

### ISSUE THREAD

**Issue by LeoPenghuawei** [rootsongjc/kubernetes-vagrant-centos-cluster#27]
I already have serval VM.
And  my VMs can't connect Internet.
Is there  an offline version?

**Comment by rootsongjc** [comment]
You can run the offline installation for Kubernetes since it uses the binary files, but the applications are running as containers, do can you get the docker images?
If you can't connect to the Internet, how do you download the docker images? Do you have a private docker registry?

**Comment by LeoPenghuawei** [comment]
Yes,I have private docker registry.

**Comment by rootsongjc** [comment]
So follow these steps:
1. clone all the images of this project into your own private Docker registry
2. change the images address in the project
3. add your private Docker registry in `--insecure-registry` list of `docker.service` file
