### ISSUE TITLE
Flannel service not started due to lack of blankspace in etcd configuration file

### ISSUE THREAD

**Issue by 2509360552** [rootsongjc/kubernetes-vagrant-centos-cluster#3]
Hi, 
Firstly, thx for bringing this great tool for k8s learning.

It is found that there is a typo in the etcd configuration file:
https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/blob/master/Vagrantfile#L156

Blankspace should be inserted bewteen "<<EOF" and "/etc/etcd/etcd-init.sh", otherwise, flannel service cannot start properly.

**Comment by rootsongjc** [comment]
@2509360552 can you show me the error messages?

**Comment by nevermosby** [comment]
@rootsongjc the file "/etc/etcd/etcd-init.sh" cannot be generated as "EOF" syntax needs the blank space. 
You can find the same syntax here: https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/blob/master/Vagrantfile#L140
