### ISSUE TITLE
Update to Istio 1.0

### ISSUE THREAD

**Issue by starjason** [rootsongjc/kubernetes-vagrant-centos-cluster#30]
grafana.yaml里的镜像还是：docker.io/istio/grafana:0.8.0

istio-demo.yaml里的文件镜像都是gcr.io的镜像，如：gcr.io/istio-release/proxyv2:1.0.0等。

**Comment by rootsongjc** [comment]
`istio-demo.yaml`文件中确实仍然使用的`gcr.io`的镜像源，我在[该commit](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/commit/0172cf1ac071891d7f91d664a48ba4e276961ffe)中将gcr.io的镜像已替换为DockerHub源，这样就不用翻墙下载了。
