### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by wjbtian** [rootsongjc/kubernetes-vagrant-centos-cluster#35]
![image](https://user-images.githubusercontent.com/6291915/44835730-a682d080-ac67-11e8-8291-ffdaf4dcc8cc.png)

安照宋总的步骤：

```bash
wget https://storage.googleapis.com/kubernetes-release/release/v1.11.0/kubernetes-client-darwin-amd64.tar.gz
```

安装kubectl，执行之后报错：Segmentation fault: 11
可能是只安装客户端的问题，我下了一个全的，就可以了。

```bash
 curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
```

 @rootsongjc song 不知道是我环境问题还是这一步确实可以改进

**Comment by rootsongjc** [comment]
我是直接下载对应平台的安装包的解压之后里面有kubectl命令，如果文档有错误，欢迎提交PR指正，这个kubectl的安装有的地方是别人补充的。

**Comment by wjbtian** [comment]
我的是mac 10.13如果有遇到同样问题的可以参考一下，问题我先关闭了，可以作为一个备考。
