### ISSUE TITLE
Can't open http://servicegraph.istio.jimmysong.io/graph, output Service Unavailable

### ISSUE THREAD

**Issue by HelloXMFJ** [rootsongjc/kubernetes-vagrant-centos-cluster#39]
```bash
kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl apply -n default -f <(istioctl kube-inject -f yaml/istio-bookinfo/bookinfo.yaml)
istioctl create -f yaml/istio-bookinfo/bookinfo-gateway.yaml
service/details created
deployment.extensions/details-v1 created
service/ratings created
deployment.extensions/ratings-v1 created
service/reviews created
deployment.extensions/reviews-v1 created
deployment.extensions/reviews-v2 created
deployment.extensions/reviews-v3 created
service/productpage created
deployment.extensions/productpage-v1 created
Created config gateway/default/bookinfo-gateway at revision 9760
Created config virtual-service/default/bookinfo at revision 9767
```
host已增加
172.17.8.102 grafana.istio.jimmysong.io
172.17.8.102 servicegraph.istio.jimmysong.io

**Comment by HelloXMFJ** [comment]
kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl -n istio-system get pod
No resources found.

**Comment by HelloXMFJ** [comment]
重新部署之后，提示如下：
 kubectl -n istio-system get pod
NAME                                        READY     STATUS              RESTARTS   AGE
grafana-586d5676db-gcrlh                    0/1       ImagePullBackOff    0          2m
istio-citadel-6df768f565-9fn9f              1/1       Running             0          2m
istio-cleanup-secrets-dp54j                 0/1       ContainerCreating   0          2m
istio-egressgateway-94db4565-vw4vp          0/1       ImagePullBackOff    0          2m
istio-galley-5b84698b94-w5ssh               0/1       ImagePullBackOff    0          2m
istio-grafana-post-install-htkxv            0/1       ContainerCreating   0          2m
istio-ingressgateway-b9d49f684-7m8tj        1/1       Running             0          2m
istio-pilot-74b8dc7bb4-68bx4                0/2       ContainerCreating   0          2m
istio-policy-864b6b8854-kqp5h               0/2       ContainerCreating   0          2m
istio-sidecar-injector-5588756989-hmbvm     0/1       ImagePullBackOff    0          2m
istio-statsd-prom-bridge-55965ff9c8-5h5rk   1/1       Running             0          2m
istio-telemetry-6d7869f6ff-r7jxh            0/2       ContainerCreating   0          2m
istio-tracing-77f9f94b98-4xt64              0/1       ImagePullBackOff    0          2m
prometheus-7456f56c96-xsgpx                 0/1       Running             0          2m
servicegraph-fffccc7fd-jb92x                0/1     ➜  kube➜  ➜ ➜➜➜➜➜


但是提示变成 ：404 page not found

**Comment by rootsongjc** [comment]
你的镜像都没有拉取下来，istio没有完全启动。

**Comment by rootsongjc** [comment]
你修改 `/etc/hosts` 了吗？增加 `172.17.8.102 grafana.istio.jimmysong.io`

**Comment by meua** [comment]
> @meua 你修改 `/etc/hosts` 了吗？增加 `172.17.8.102 grafana.istio.jimmysong.io`
添加了，grafana.istio.jimmysong.io可以正常访问，但是http://servicegraph.istio.jimmysong.io/访问不了（也添加到host了）

**Comment by rootsongjc** [comment]
@meua 你查看下 `servicegraph` 的服务状态，还有 ingress 配置是否有添加。
