### ISSUE TITLE
 error: unable to forward port because pod is not running. Current status=Pending

### ISSUE THREAD

**Issue by HelloXMFJ** [rootsongjc/kubernetes-vagrant-centos-cluster#40]
```bash
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl -n default port-forward $(kubectl -n default get pod -l app=vistio-api -o jsonpath='{.items[0].metadata.name}') 9091:9091 &
[1] 13333
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ error: unable to forward port because pod is not running. Current status=Pending

[1]  + 13333 exit 1     kubectl -n default port-forward  9091:9091
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl -n default port-forward $(kubectl -n default get pod -l app=vistio-web -o jsonpath='{.items[0].metadata.name}') 8080:8080 &
[1] 13375
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ error: unable to forward port because pod is not running. Current status=Pending

[1]  + 13375 exit 1     kubectl -n default port-forward  8080:8080
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
node1     Ready     <none>    2d        v1.9.1
node2     Ready     <none>    2d        v1.9.1
node3     Ready     <none>    2d        v1.9.1
```

**Comment by HelloXMFJ** [comment]
➜  kubernetes-vagrant-centos-cluster git:(master) ✗ kubectl apply -n default -f <(istioctl kube-inject -f yaml/istio-bookinfo/bookinfo.yaml)
istioctl create -f yaml/istio-bookinfo/bookinfo-gateway.yaml
service/details created
deployment.extensions/details-v1 created
service/ratings created
deployment.extensions/ratings-v1 created
service/reviews created
deployment.extensions/reviews-v1 created
deployment.extensions/reviews-v2 created
deployment.extensions/reviews-v3 created
service/productpage created
deployment.extensions/productpage-v1 created
Created config gateway/default/bookinfo-gateway at revision 9760
Created config virtual-service/default/bookinfo at revision 9767

**Comment by rootsongjc** [comment]
Please check if the `vistio-api` pod is running.

**Comment by rootsongjc** [comment]
已不建议使用 vistio。
