### ISSUE TITLE
Unable to open https://172.17.8.101:8443/

### ISSUE THREAD

**Issue by 0312birdzhang** [rootsongjc/kubernetes-vagrant-centos-cluster#41]
```
您的连接不是私密连接
攻击者可能会试图从 172.17.8.101 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_INVALID
```
**OS:** Windows 10
**Browser:** Chrome 69.0.3497.100
**Kubernetes version:** 1.11.3

把ca.pem转换成ca.crt导入之后还是同样的提示，这个是要怎么操作？
P.S. 虽然我看到说不支持Windows，但是还是顺利的安装完成了

**Comment by 0312birdzhang** [comment]
@rootsongjc  并没有跳过的选项，应该是证书的问题。我用这个方式解决了 https://github.com/kubernetes/dashboard/issues/2954#issuecomment-385354244 ，现在可以跳过了。

安装失败可能是`./dns-deploy.sh -r 10.254.0.0/16 -i 10.254.0.2 |kubectl apply -f -` 这个编码的问题，我是ssh进去然后vim下`:set ff=unix`然后手动执行了一下就可以了。

**Comment by 0312birdzhang** [comment]
不过上面的方法好像也有问题，dashboard进去之后一堆提示没有权限 😂 
![image](https://user-images.githubusercontent.com/1762041/46120418-263d9400-c242-11e8-95f7-e414680f7a65.png)

**Comment by 0312birdzhang** [comment]
非常完美，感谢 👍 

![image](https://user-images.githubusercontent.com/1762041/46120483-7c123c00-c242-11e8-8456-bad613acd0c1.png)

**Comment by rootsongjc** [comment]
@0312birdzhang 欢迎在文档中补充Windows上安装的注意事项。你是我见过的第一个在Windows上成功安装的。

**Comment by 0312birdzhang** [comment]
@rootsongjc 好的 😃

**Comment by rootsongjc** [comment]
文档已更新，https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/42 和 https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/43 增加了对 Windows 支持的描述。
