### ISSUE TITLE
Restart Error

### ISSUE THREAD

**Issue by ZQiannnn** [rootsongjc/kubernetes-vagrant-centos-cluster#47]
# Environment

- OS:
- Kubernetes version: 1.9.1
- VirtualBox version:5.2.18
- Vagrant version:2.1.5

## What I did?

重启之后，集群不启动
![image](https://user-images.githubusercontent.com/19886406/47125525-b3f72700-d2b6-11e8-8cfa-57a2097ca1a5.png)

## Messages

Logs or error messages.

**Comment by rootsongjc** [comment]
目前不支持虚拟机关机、重启后kubernetes集群自动拉起，只能销毁后重建集群。
You need to rebuild the cluster while halt or restart the vagrant cluster.

**Comment by rootsongjc** [comment]
Duplicated with #23
