### ISSUE TITLE
CRLF line separator in systemd unit files when using Vagrant in windows

### ISSUE THREAD

**Issue by senthilrch** [rootsongjc/kubernetes-vagrant-centos-cluster#50]
# Environment

- OS: Windows 8.1
- Kubernetes version: v1.11
- VirtualBox version: v5.0
- Vagrant version: v2.2.0

## What I did?

I cloned the repo to my Windows 8.1 laptop. Followed the instructions in README.md to install a 3-node kubernetes cluster using Vagrant/Virtualbox. None of the nodes bootstrapped successfully. 

## Messages

Upon investigating the issue I found the reason. The systemd unit files for the master and worker services has CRLF line separator. Whereas CentOS is a Linux OS and it expects LF as line separator. I used dos2unix utility and replaced the CRLF with LF in all the unit files, then started the services manually. After that nodes bootstrapped successfully and kubernetes cluster was up and running.

**Comment by rootsongjc** [comment]
@senthilrch I think the README doc has mentioned that attention point in windows. Because I have no Windows laptop, so I can't test it for compatibility. Maybe that's a little tricky, feel free to add the missing parts about running kubernetes cluster in windows in README doc. Thank you.
