### ISSUE TITLE
Grafana did not show normal 

### ISSUE THREAD

**Issue by haiyuancheng** [rootsongjc/kubernetes-vagrant-centos-cluster#61]
Grafana 可以正常进入访问，但是没有dashborad, datasource 也没有

**Comment by rootsongjc** [comment]
你能提供下 grafana 的日志吗？

**Comment by haiyuancheng** [comment]
下面是我的grafana 日志信息  
[I] 2019-02-20T02:06:58Z InfluxDB starting, version unknown, branch unknown, commit unknown
[I] 2019-02-20T02:06:58Z Go version go1.8.3, GOMAXPROCS set to 1
[I] 2019-02-20T02:06:58Z Using configuration at: /etc/config.toml
 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
[I] 2019-02-20T02:07:38Z Using data dir: /data/data service=store
[I] 2019-02-20T02:07:38Z opened service service=subscriber
[I] 2019-02-20T02:07:38Z Starting monitor system service=monitor
[I] 2019-02-20T02:07:38Z 'build' registered for diagnostics monitoring service=monitor
[I] 2019-02-20T02:07:38Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2019-02-20T02:07:38Z 'network' registered for diagnostics monitoring service=monitor
[I] 2019-02-20T02:07:38Z 'system' registered for diagnostics monitoring service=monitor
[I] 2019-02-20T02:07:38Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2019-02-20T02:07:38Z Starting snapshot service service=snapshot
[I] 2019-02-20T02:07:38Z Starting continuous query service service=continuous_querier
[I] 2019-02-20T02:07:38Z Starting HTTP service service=httpd
[I] 2019-02-20T02:07:38Z Authentication enabled:false service=httpd
[I] 2019-02-20T02:07:38Z Listening on HTTP:[::]:8086 service=httpd
[I] 2019-02-20T02:07:38Z Starting retention policy enforcement service with check interval of 30m0s service=retention
[I] 2019-02-20T02:07:38Z Listening for signals
[I] 2019-02-20T02:07:38Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
[I] 2019-02-20T02:37:38Z retention policy shard deletion check commencing service=retention

**Comment by haiyuancheng** [comment]
好滴，抽时间看哈这块儿。
我在 heapster 中发现了这个，感觉是网络那里出了问题，内部连接不上heapster 连接不上influxdb 
 E0220 06:59:45.023312       1 influxdb.go:208] Failed to create influxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb on 10.254.0.2:53: read udp 172.33.78.2:52347-&gt;10.254.0.2:53: i/o timeout

**Comment by rootsongjc** [comment]
检查下 CoreDNS 是否工作正常，内部域名是否能够解析。

**Comment by haiyuancheng** [comment]
非常感谢，已经解决，估计是在调用install.sh 时候 cd /vagrant/addon/dns/
    ./dns-deploy.sh -r 10.254.0.0/16 -i 10.254.0.2 |kubectl apply -f -  失败，所以CoreDNS 没有运行，
I0220 09:36:05.031490       1 influxdb.go:274] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"

**Comment by Paladinhanxiao** [comment]
> 非常感谢，已经解决，估计是在调用install.sh 时候 cd /vagrant/addon/dns/
> ./dns-deploy.sh -r 10.254.0.0/16 -i 10.254.0.2 |kubectl apply -f - 失败，所以CoreDNS 没有运行，
> I0220 09:36:05.031490 1 influxdb.go:274] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"

您好，我也遇到相同问题了，您是怎么解决的？
