### ISSUE TITLE
IP that cannot Ping through pod on the master node

### ISSUE THREAD

**Issue by yuri-li** [rootsongjc/kubernetes-vagrant-centos-cluster#62]
# Environment

- OS: windows 10 64
- Kubernetes version:  1.13.0
- VirtualBox version: 6.0.4
- Vagrant version:  2.2.3

## What I did?

1.  kubectl get pod -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP  
nginx-deployment-**        1/1         Running   0                 9s    172.18.0.2

2.  ping 172.18.0.2
failed

**Comment by yuri-li** [comment]
![image](https://user-images.githubusercontent.com/7019517/53235077-f1881880-36cb-11e9-8cbc-efc9a7cfb365.png)

**Comment by yuri-li** [comment]
![image](https://user-images.githubusercontent.com/7019517/53235207-42980c80-36cc-11e9-8c90-2432f0b4e95f.png)

**Comment by rootsongjc** [comment]
Please check your VirtualBox config, especially the network config items. Make sure you're using the NAT network.

**Comment by yuri-li** [comment]
![image](https://user-images.githubusercontent.com/7019517/53236729-f2bb4480-36cf-11e9-8ee2-017f324c782a.png)

**Comment by yuri-li** [comment]
![image](https://user-images.githubusercontent.com/7019517/53243209-230bde80-36e2-11e9-9a06-652fd0fd37ab.png)

**Comment by yuri-li** [comment]
![image](https://user-images.githubusercontent.com/7019517/53244142-f0afb080-36e4-11e9-93c5-940b11d2e4f4.png)

**Comment by yuri-li** [comment]
是我的错。
排查问题的过程：
1、没有flannel0的网卡，所以，flannel没有正常启动
按照[rootsongjc](/rootsongjc)的脚本，没有flannel0的网卡，而是使用eth1。所以，不能以没有flannel0的网卡为依据
2、flannel没有正常启动，所以，网络不通
我排查了etcd中的记录，没有发现明显的问题。或许是我调试的过程中，把配置改错了。

当然，我不了解etcd与flannel的配置。
很幸运，删掉3台vm，重新安装后，等node全部ready，且，virtualbox网络下载的流量归0后，再次重试，可以ping通pod的ip了。赞。
注：node全部ready后，virtualbox在大约5分钟内，貌似还在下载什么文件。也可能是“360加速球”报告错了。总之，问题最终还是锁定了，是flannel配置有问题，但具体是哪里配错了，没有找到。
好在，问题终究解决了

**Comment by yuri-li** [comment]
问题最终还是找到了: `vagrant halt`后，etcd中存储的数据丢失了。
排查命令：`etcdctl get /kube-centos/network/config`
song给的脚本里，相关的配置都写死了，重启即可自动修复。
于是，还有两个问题：
1、etcd为什么会丢失数据？
2、除了`vagrant up`外，还有更快捷的方法吗？
