### ISSUE TITLE
node1: /tmp/vagrant-shell: line 214: kubectl: command not found

### ISSUE THREAD

**Issue by kamal2222ahmed** [rootsongjc/kubernetes-vagrant-centos-cluster#65]
# Environment

- OS: Mac OSX 10.14.2
- Kubernetes version:
- VirtualBox version: 5.2.24
- Vagrant version:
Vagrant 2.2.1

## What I did?
vagrant up 
Your operations on this repo.

## Messages

Logs or error messages.

```
node1: cp: cannot stat ‘/vagrant/kubernetes/server/bin/*’: No such file or directory
    node1: configure master and node1
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-apiserver.service to /usr/lib/systemd/system/kube-apiserver.service.
    node1: Job for kube-apiserver.service failed because the control process exited with error code. See "systemctl status kube-apiserver.service" and "journalctl -xe" for details.
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-controller-manager.service to /usr/lib/systemd/system/kube-controller-manager.service.
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-scheduler.service to /usr/lib/systemd/system/kube-scheduler.service.
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
    node1: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
    node1: Configure Kubectl to autocomplete
    node1: /tmp/vagrant-shell: line 214: kubectl: command not found
```

**Comment by kamal2222ahmed** [comment]
node3: cp: cannot stat ‘/vagrant/kubernetes/server/bin/*’: No such file or directory
    node3: configure node3
    node3: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
    node3: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
    node3: deploy coredns
    node3: /tmp/vagrant-shell: line 198: kubectl: command not found
    node3: /home/vagrant
    node3: deploy kubernetes dashboard
    node3: /tmp/vagrant-shell: line 202: kubectl: command not found
    node3: create admin role token
    node3: /tmp/vagrant-shell: line 204: kubectl: command not found
    node3: the admin role token is:
    node3: /tmp/vagrant-shell: line 206: kubectl: command not found
    node3: /tmp/vagrant-shell: line 206: kubectl: command not found
    node3: login to dashboard with the above token
    node3: /tmp/vagrant-shell: line 208: kubectl: command not found
    node3: https://172.17.8.101:
    node3: install traefik ingress controller
    node3: /tmp/vagrant-shell: line 210: kubectl: command not found
    node3: Configure Kubectl to autocomplete
    node3: /tmp/vagrant-shell: line 214: kubectl: command not found

**Comment by rootsongjc** [comment]
You can login to the virtual machine, any node is OK, to check if the path `/vagrant/kubernetes/server/bin/` really exist. It should be mounted with NFS.

**Comment by crydemon** [comment]
你解决了吗

**Comment by crydemon** [comment]
下载k8s地址可能失效了 新的： https://dl.k8s.io/v1.13.4/kubernetes-server-linux-amd64.tar.gz

**Comment by xiahuhu1** [comment]
我也出现了这种情况，下载的k8s文件有问题，那现在怎么重先安装啊？

**Comment by congim** [comment]
@rootsongjc  我下载1.13.0的releases压缩文件，并且将文件重命名为kubernetes-server-linux-amd64.tar.gz， 还是会报
```log
 node2: kubernetes/client/
    node2: kubernetes/client/README
    node2: cp: cannot stat ‘/vagrant/kubernetes/server/bin/*’: No such file or directory
    node2: configure node2
    node2: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
    node2: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
    node2: Configure Kubectl to autocomplete
    node2: /tmp/vagrant-shell: line 214: kubectl: command not found
```
登录到node2 node3 node1都是能看到/vagrant/kubernetes/server/目录的，但是没有server/bin/目录，这个是k8s打包的问题吗

**Comment by congim** [comment]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/10218415/62684997-66d67400-b9f4-11e9-80e4-adf761d901b8.png">

flanneld倒是启动起来了

**Comment by congim** [comment]
github里面的安装包是错误的，使用
```conf
https://storage.googleapis.com/kubernetes-release/release/v1.13.0/kubernetes-server-linux-amd64.tar.gz
```
自己改版本号对号入座

**Comment by rootsongjc** [comment]
请问安装包有什么错误？@congim

**Comment by congim** [comment]
@rootsongjc 里面缺文件，我用这个地址下载的安装包就好了

https://storage.googleapis.com/kubernetes-release/release/v1.13.0/kubernetes-server-linux-amd64.tar.gz
