### ISSUE TITLE
Change the flannel to calico

### ISSUE THREAD

**Issue by xieydd** [rootsongjc/kubernetes-vagrant-centos-cluster#69]
# Environment

- OS:
- Kubernetes version:
- VirtualBox version:
- Vagrant version:

## What I did?

Hi, jimmy @rootsongjc . If i want to change the flannel to calico, how can  i do it? And if i want to update the kubernetes version 1.11 to 1.13, how can i do it? Thanks  a lot.

## Messages

Logs or error messages.

**Comment by rootsongjc** [comment]
You can download the latest version of Kubernetes and replace the original tar package.
I have not used calico, in order to keep this environment simple flannel is more easy to install.

**Comment by xieydd** [comment]
Thanks for your reply.I got it.
