### ISSUE TITLE
Kubelet server start failed - v1.10.0

### ISSUE THREAD

**Issue by pengisgood** [rootsongjc/kubernetes-vagrant-centos-cluster#7]
In this [PR](https://github.com/kubernetes/kops/pull/4357), the `--require-kubeconfig` flag has been removed.

When I use these scripts to setup cluster with kubelet version `1.10.0`, it will failed due to the unknown flag `--require-kubeconfig`.

After I removed this flag in the kubelet config file, it worked.

**Comment by pengisgood** [comment]
I created a PR at here https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/pull/8

**Comment by rootsongjc** [comment]
@pengisgood I think this a compatibility problem.

**Comment by pengisgood** [comment]
The kubelet can start now after removing this flag.
