### ISSUE TITLE
安装过程电脑卡死

### ISSUE THREAD

**Issue by sunnywa** [rootsongjc/kubernetes-vagrant-centos-cluster#74]
# Environment

- OS: macos 10.14.5
- Kubernetes version: 
- VirtualBox version:5.2.18
- Vagrant version:2.2.4

## What I did?
安装过程电脑卡死。

## Messages

Logs or error messages.

**Comment by rootsongjc** [comment]
在哪一步卡住？Kubernetes 用的什么版本？

**Comment by rootsongjc** [comment]
长时间未回复详细信息，关闭该 issue。
