### ISSUE TITLE
vagrant up 后 https://172.17.8.101:8443 不显示首页

### ISSUE THREAD

**Issue by xinzhaizisunqi** [rootsongjc/kubernetes-vagrant-centos-cluster#76]
您好，宋老师
 安装过程中无报错，但是安装完成后输入https://172.17.8.101:8443 显示无法访问
是因为这俩东西没拖动到文件夹里么？
kubernetes-client-linux-amd64.tar.gz
kubernetes-server-linux-amd64.tar.gz

**Comment by rootsongjc** [comment]
Kubernetes 启动好了吗？默认安装过程中会自动下载 kubernetes 的，不需要你手动下载。

**Comment by xinzhaizisunqi** [comment]
宋老师，启动成功了，不过使用的kubeadm，使用kubernetes-vagrant-centos-cluster重新安装多次后每一次 机器内存不够，总是在第三个节点得时候内存就达到了7.9G，感谢您的回复，接下来拜读文档。

**Comment by rootsongjc** [comment]
使用 vagrant 安装的方式确实很占内存，如果仅仅是试用 kubenretes 的话可以直接使用 Docker for mac 里内置的 kubernetes 集群，一键启动即可。

**Comment by fuxinghua** [comment]
如果是 kubernetes 1.15版本有几个地方要修改下： 
1. node1/kubelet、node2/kubelet、node3/kubelet ， 去掉：--allow-privileged=true ;  
2. config/config 注释掉：KUBE_ALLOW_PRIV="--allow-privileged=true"

**Comment by rootsongjc** [comment]
该示例尚未在 Kubernetes 1.15 中验证，@fuxinghua 如果你有验证过欢迎更新。

**Comment by rootsongjc** [comment]
@fuxinghua 代码已更新到支持 Kubernetes 1.15，感谢反馈。
