### ISSUE TITLE
打不开dashboard

### ISSUE THREAD

**Issue by xinzhaizisunqi** [rootsongjc/kubernetes-vagrant-centos-cluster#77]
#
window10

- OS:
- Kubernetes version:1.9.1
- VirtualBox version:6.0.8
- Vagrant version:2.2.5

## What I did?

Your operations on this repo.

## Messages
https://172.17.8.101:6443/ 仍然打不开页面

![image](https://user-images.githubusercontent.com/34813785/61141054-46072580-a4ff-11e9-85fd-aa6f70a678c7.png)

**Comment by rootsongjc** [comment]
Is the dashboard running?
```bash
kubectl get pod -n kube-system
```

**Comment by rootsongjc** [comment]
请下载最新版本的代码，我已经在 Kubernetes1.15 中测试过了，可以正常运行。
