### ISSUE TITLE
无法挂载 /vagrant

### ISSUE THREAD

**Issue by caitui** [rootsongjc/kubernetes-vagrant-centos-cluster#81]
# Environment

- OS: win10
- Kubernetes version:
- VirtualBox version:
- Vagrant version:

## What I did?

对 / 目录执行 ls 卡死，用 strace 查看，发现挂载 /vagrant 时卡死
```
strace ls --color=auto /

lstat("/srv", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
lstat("/swapfile", {st_mode=S_IFREG|0600, st_size=2147483648, ...}) = 0
capget({_LINUX_CAPABILITY_VERSION_3, 0}, NULL) = 0
getxattr("/swapfile", "security.capability", 0x7ffdbfa1f0b0, 20) = -1 ENODATA (No data available)
lstat("/vagrant",
```

## Messages

Logs or error messages.

**Comment by rootsongjc** [comment]
Repo has been updated. Refer to https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/78
