### ISSUE TITLE
After `vagrant up`: chmod: cannot access ‘/etc/systemd/system/docker.service.d/http-proxy.conf’: No such file or directory

### ISSUE THREAD

**Issue by YoungWilliamZ** [rootsongjc/kubernetes-vagrant-centos-cluster#82]
# Environment

- OS: macOS 10.14.4 (18E224)
- Kubernetes version: 1.15.0
- VirtualBox version: 6.0.10 r132072 (Qt5.6.3)
- Vagrant version: 2.2.5

## What I did?

I just cloned this repo and used `vagrant up`, then get the error messages below.

## Messages

The following error messages is the same as node1. 

```
    ...
    node2: configure node2
    node2: Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /usr/lib/systemd/system/kubelet.service.
    node2: Created symlink from /etc/systemd/system/multi-user.target.wants/kube-proxy.service to /usr/lib/systemd/system/kube-proxy.service.
    node2: Configure Kubectl to autocomplete
==> node2: Configuring proxy for Docker...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod 0644 /etc/systemd/system/docker.service.d/http-proxy.conf

Stdout from the command:



Stderr from the command:

chmod: cannot access ‘/etc/systemd/system/docker.service.d/http-proxy.conf’: No such file or directory
```

I fixed it through the following operations in `node1`. After I sshed into the node1 and touched a new empty `/etc/systemd/system/docker.service.d/http-proxy.conf`, then everything was OK for node1. But the same thing happened in the `node2`. I thought this may be a bug and i didn't find an issue on this rep, therefore I open this issue looking for help. Thanks.

**Comment by rootsongjc** [comment]
@YoungWilliamZ This is a bug which has been solved just now.

**Comment by xtay315** [comment]
@rootsongjc  how to solved it , l have the same problem too.

**Comment by rootsongjc** [comment]
Can you paste your error messages here? @xtay315

**Comment by xtay315** [comment]
downgrade the plugin 
vagrant plugin install --plugin-version 2.0.1 vagrant-proxyconf
or
changed ~/.vagrant.d/gems/${version}/gems/vagrant-proxyconf-${version}/lib/vagrant-proxyconf/action/configure_docker_proxy.rb like this:
tmp = Tempfile.new('vagrant-proxyconf-docker-config.json')
@docker_client_config_path = tmp.path

@rootsongjc

**Comment by rootsongjc** [comment]
@xtay315 can you make a PR to fix this bug?

**Comment by fty4** [comment]
As already mentioned here ist the issue from the plugin:
https://github.com/tmatilai/vagrant-proxyconf/issues/206

PR: https://github.com/tmatilai/vagrant-proxyconf/pull/208
