### ISSUE TITLE
会卡在mounting NFS shared folders这一步

### ISSUE THREAD

**Issue by hxr2333** [rootsongjc/kubernetes-vagrant-centos-cluster#83]
# Environment

- OS:centos7.6
- Kubernetes version:
- VirtualBox version:6.0.10
- Vagrant version:2.2.5

## What I did?
在下载完项目需要的文件后执行vagrant up 卡在mounting NFS shared folders这一步
Your operations on this repo.

## Messages

Logs or error messages.

==> node1: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 172.17.8.1:/home/duoyi/kubernetes-vagrant-centos-cluster-master /vagrant

Stdout from the command:

Stderr from the command:

mount.nfs: No route to host

**Comment by hxr2333** [comment]
将Vagrantfile中的config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false
改为
config.vm.synced_folder ".", "/vagrant", type: "rsync"
改成用rsync的方式传输kubernetes的安装包，就可以正常执行安装流程，看来有可能是NFS没法正常在系统中安装，或者安装时间过长

**Comment by rootsongjc** [comment]
@hxr2333 solved
