### ISSUE TITLE
vagrant up后在node1: SSH auth method: private key这里timed out

### ISSUE THREAD

**Issue by likeweilikewei** [rootsongjc/kubernetes-vagrant-centos-cluster#95]
# Environment

- OS:CentOS release 6.10 (Final)
- Kubernetes version:1.9.1
- VirtualBox version:VirtualBox-5.2-5.2.44_139111_el6-1.x86_64
- Vagrant version:vagrant-2.2.0-1.x86_64

## What I did?
在vagrant up后等一会就报错
试过修改config.vm.boot_timeout也没用

## Messages
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
==> node1: Importing base box 'centos/7'...
==> node1: Matching MAC address for NAT networking...
==> node1: Setting the name of the VM: node1
==> node1: Clearing any previously set network interfaces...
==> node1: Preparing network interfaces based on configuration...
    node1: Adapter 1: nat
    node1: Adapter 2: hostonly
==> node1: Forwarding ports...
    node1: 22 (guest) => 2222 (host) (adapter 1)
==> node1: Running 'pre-boot' VM customizations...
==> node1: Booting VM...
==> node1: Waiting for machine to boot. This may take a few minutes...
    node1: SSH address: 127.0.0.1:2222
    node1: SSH username: vagrant
    node1: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by rootsongjc** [comment]
看样子是第一个虚拟机就没启动成功，你可以使用 `vagrant ssh node1` 吗？

**Comment by likeweilikewei** [comment]
> 看样子是第一个虚拟机就没启动成功，你可以使用 `vagrant ssh node1` 吗？

感谢大神回复，访问不了node1，直接超时，我的cpu不支持虚拟化有影响吗

**Comment by rootsongjc** [comment]
肯定得CPU 支持虚拟化才行啊！

**Comment by likeweilikewei** [comment]
大神，那还有其他办法部署Kubernetes吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rootsongjc/kubernetes-vagrant-centos-cluster"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 中午12:22
收件人:&nbsp;"rootsongjc/kubernetes-vagrant-centos-cluster"<kubernetes-vagrant-centos-cluster@noreply.github.com&gt;;
抄送:&nbsp;"罗伯特·德尼罗"<1293120583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootsongjc/kubernetes-vagrant-centos-cluster] vagrant up后在node1: SSH auth method: private key这里timed out (#95)





 
肯定得CPU 支持虚拟化才行啊！

**Comment by rootsongjc** [comment]
这就要看你是在什么环境下部署，出于什么目的安装 Kubernetes 了。

**Comment by likeweilikewei** [comment]
还是在这台服务器上，目的是学习Kubernetes，和大神的git项目一样，有个本地学习环境，请问有方法吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rootsongjc/kubernetes-vagrant-centos-cluster"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 中午12:34
收件人:&nbsp;"rootsongjc/kubernetes-vagrant-centos-cluster"<kubernetes-vagrant-centos-cluster@noreply.github.com&gt;;
抄送:&nbsp;"罗伯特·德尼罗"<1293120583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootsongjc/kubernetes-vagrant-centos-cluster] vagrant up后在node1: SSH auth method: private key这里timed out (#95)





 
这就要看你是在什么环境下部署，出于什么目的安装 Kubernetes 了。

**Comment by rootsongjc** [comment]
你是在 CentOS 的服务器上安装？你自己的电脑上安装虚拟机可以吗？

**Comment by likeweilikewei** [comment]
目前是在CentOS安装的，自己是mac，安装也可以，就是电脑资源有点紧张


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rootsongjc/kubernetes-vagrant-centos-cluster"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 中午12:54
收件人:&nbsp;"rootsongjc/kubernetes-vagrant-centos-cluster"<kubernetes-vagrant-centos-cluster@noreply.github.com&gt;;
抄送:&nbsp;"罗伯特·德尼罗"<1293120583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rootsongjc/kubernetes-vagrant-centos-cluster] vagrant up后在node1: SSH auth method: private key这里timed out (#95)





 
你是在 CentOS 的服务器上安装？你自己的电脑上安装虚拟机可以吗？

**Comment by likeweilikewei** [comment]
CPU不支持虚拟化造成

**Comment by likeweilikewei** [comment]
> 你是在 CentOS 的服务器上安装？你自己的电脑上安装虚拟机可以吗？

谢谢指教
